export * from './header/Header'
export * from './home/Home'
export * from './about/About'
export * from './skills/Skills'
export * from './projects/Projects'
export * from './my-github/MyGitHub'
export * from './contact/Contact'
export * from './footer/Footer'
